# Generated by Django 4.2.7 on 2023-11-29 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('locality', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=50)),
                ('mobile', models.IntegerField(default=0)),
                ('zipcode', models.IntegerField()),
                ('state', models.CharField(choices=[('Amazonas', 'Leticia'), ('Antioquia', 'Medellín'), ('Arauca', 'Arauca'), ('Atlántico', 'Barranquilla'), ('Bolívar', 'Cartagena'), ('Boyacá', 'Tunja'), ('Caldas', 'Manizales'), ('Caquetá', 'Florencia'), ('Casanare', 'Yopal'), ('Cauca', 'Popayán'), ('Cesar', 'Valledupar'), ('Chocó', 'Quibdó'), ('Córdoba', 'Montería'), ('Cundinamarca', 'Bogotá, D.C.'), ('Guainía', 'Inírida'), ('Guaviare', 'San José del Guaviare'), ('Huila', 'Neiva'), ('La Guajira', 'Riohacha'), ('Magdalena', 'Santa Marta'), ('Meta', 'Villavicencio'), ('Nariño', 'Pasto'), ('Norte de Santander', 'Cúcuta'), ('Putumayo', 'Mocoa'), ('Quindío', 'Armenia'), ('Risaralda', 'Pereira'), ('San Andrés y Providencia', 'San Andrés'), ('Santander', 'Bucaramanga'), ('Sucre', 'Sincelejo'), ('Tolima', 'Ibagué'), ('Valle del Cauca', 'Cali'), ('Vaupés', 'Mitú'), ('Vichada', 'Puerto Carreño')], max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
