# Generated by Django 4.2.7 on 2023-11-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='zipcode',
            new_name='identificacion',
        ),
    ]
