# Generated by Django 4.2.7 on 2023-11-30 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_zipcode_customer_identificacion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='mobile',
            new_name='celular',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='state',
            new_name='departamento',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='locality',
            new_name='direccion',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='name',
            new_name='nombre',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='city',
        ),
        migrations.AddField(
            model_name='customer',
            name='telefono',
            field=models.IntegerField(default=0),
        ),
    ]
