# Generated by Django 4.2.7 on 2023-11-30 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('CR', 'Ropa casual'), ('ML', 'Maquillaje'), ('LS', 'Calzado'), ('MS', 'Perfumes'), ('PN', 'Ropa interior'), ('GH', 'Accesorios'), ('CZ', 'Chaquetas'), ('IC', 'Bolsos')], max_length=2),
        ),
    ]
