# Generated by Django 4.2.8 on 2023-12-14 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_cart_options_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodapp',
            new_name='pais_origen',
        ),
    ]
