# Generated by Django 4.2.8 on 2023-12-14 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_rename_prodapp_product_pais_origen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='composition',
            new_name='referencia',
        ),
    ]
