# Generated by Django 4.2.8 on 2023-12-14 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_rename_composition_product_referencia'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='selling_price',
            new_name='precio_venta',
        ),
    ]
