# Generated by Django 4.2.8 on 2023-12-16 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_selling_price_product_precio_venta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_image',
            new_name='imagen_producto',
        ),
    ]
