# Generated by Django 4.2.8 on 2023-12-16 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_alter_product_pais_origen'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='descripcion',
        ),
    ]
