# Generated by Django 4.2.8 on 2023-12-17 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_rename_category_product_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='quantity',
            new_name='cantidad',
        ),
        migrations.RenameField(
            model_name='orderplaced',
            old_name='quantity',
            new_name='cantidad',
        ),
    ]
