# Generated by Django 4.2.8 on 2023-12-17 06:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_rename_quantity_cart_cantidad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='title',
            new_name='titulo_producto',
        ),
    ]
