# Generated by Django 4.2.8 on 2023-12-18 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_rename_amount_payment_valor_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='valor_total',
            new_name='amount',
        ),
    ]
