# Generated by Django 4.2.8 on 2023-12-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_rename_valor_total_payment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='categoria',
            field=models.CharField(choices=[('RC', 'Ropa casual'), ('ME', 'Maquillaje'), ('CO', 'Calzado'), ('PS', 'Perfumes'), ('RI', 'Ropa interior'), ('AS', 'Accesorios'), ('CS', 'Chaquetas'), ('BS', 'Bolsos')], max_length=2),
        ),
    ]
