# Generated by Django 4.2.8 on 2024-01-06 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0033_rename_status_orderplaced_estado_de_entrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='estado_de_entrega',
            new_name='status',
        ),
    ]
