# Generated by Django 4.2.8 on 2024-01-06 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_rename_estado_de_entrega_orderplaced_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderplaced',
            name='status',
            field=models.CharField(choices=[('Aceptado', 'Aceptado'), ('Empacado', 'Empacado'), ('En camino', 'En camino'), ('Entregado', 'Entregado'), ('Cancelado', 'Cancelado'), ('Pendiente', 'Pendiente')], default='Pendiente', max_length=50),
        ),
    ]
